import type { PuzzleConfig } from '../types';

export const puzzles: PuzzleConfig[] = [
  {
    id: 1,
    title: 'Love Letter Decoder',
    subtitle: 'Day 1 of 10',
    description: 'A secret love letter has been encrypted with a Caesar Cipher. Shift the letters to reveal the hidden message!',
    unlockDate: '2026-02-04',
    type: 'cipher',
    clue: btoa('The city is Oslo — your adventure begins in Norway\'s capital!'),
    icon: '🔐',
  },
  {
    id: 2,
    title: 'The Royal Riddle',
    subtitle: 'Day 2 of 10',
    description: 'Solve three riddles that lead you to a royal street. Each answer brings you closer to the Queen\'s path!',
    unlockDate: '2026-02-05',
    type: 'riddle',
    clue: btoa('Dronningens... (Queen\'s in Norwegian)'),
    icon: '👑',
  },
  {
    id: 3,
    title: 'Words of Love',
    subtitle: 'Day 3 of 10',
    description: 'Search through a 12x12 grid to find 8 hidden romance words. Look in every direction!',
    unlockDate: '2026-02-06',
    type: 'wordsearch',
    clue: btoa('...gate (meaning \'street\' in Norwegian)'),
    icon: '🔍',
  },
  {
    id: 4,
    title: 'Memory Match',
    subtitle: 'Day 4 of 10',
    description: 'Match all the pairs in this 4x4 card game, then solve a quick math puzzle to unlock your clue!',
    unlockDate: '2026-02-07',
    type: 'memory',
    clue: btoa('The address number is 25'),
    icon: '🃏',
  },
  {
    id: 5,
    title: 'Sudoku of Love',
    subtitle: 'Day 5 of 10',
    description: 'Complete this mini 4x4 Sudoku using the digits 1, 2, 5, and 6. Every row, column, and box needs all four!',
    unlockDate: '2026-02-08',
    type: 'sudoku',
    clue: btoa('The first digit of the address is 2...'),
    icon: '🔢',
  },
  {
    id: 6,
    title: 'Crossword Connection',
    subtitle: 'Day 6 of 10',
    description: 'Fill in this small themed crossword. Every answer is connected to love and romance!',
    unlockDate: '2026-02-09',
    type: 'crossword',
    clue: btoa('...and the second digit is 5, making it 25!'),
    icon: '📝',
  },
  {
    id: 7,
    title: 'Heart Maze',
    subtitle: 'Day 7 of 10',
    description: 'Navigate through a heart-shaped maze to find the path to your next clue!',
    unlockDate: '2026-02-10',
    type: 'maze',
    clue: btoa('Something sweet awaits you there...'),
    icon: '💗',
  },
  {
    id: 8,
    title: 'Scrambled Romance',
    subtitle: 'Day 8 of 10',
    description: 'Unscramble 5 jumbled words — all related to love and romance. Can you figure them all out?',
    unlockDate: '2026-02-11',
    type: 'anagram',
    clue: btoa('A cozy cafe or restaurant...'),
    icon: '🔤',
  },
  {
    id: 9,
    title: 'Love & Oslo Trivia',
    subtitle: 'Day 9 of 10',
    description: 'Answer 8 questions about love and Oslo. You need at least 6 correct to unlock the clue!',
    unlockDate: '2026-02-12',
    type: 'trivia',
    clue: btoa('Arrive at 18:00 on February 14th'),
    icon: '❓',
  },
  {
    id: 10,
    title: 'The Final Piece',
    subtitle: 'Day 10 of 10',
    description: 'Drag and drop the pieces to complete a 4x4 jigsaw puzzle and reveal the final message!',
    unlockDate: '2026-02-13',
    type: 'jigsaw',
    clue: btoa('The full address: Dronningens gate 25, Oslo. See you on Valentine\'s Day, Julie! \u{1F495}'),
    icon: '🧩',
  },
];
