import type { PuzzleConfig } from '../types';

export const puzzles: PuzzleConfig[] = [
  {
    id: 1,
    title: 'The Stable',
    subtitle: 'Day 1 of 7',
    description: 'Something about these beautiful creatures reminds me of you, Julie. Match each one to where it belongs.',
    unlockDate: '2026-02-07',
    type: 'horses_match',
    clue: btoa('The city is Oslo \u2014 your adventure begins in Norway\'s capital!'),
    icon: '\uD83D\uDC0E',
    theme: 'emerald',
  },
  {
    id: 2,
    title: 'The Battle Within',
    subtitle: 'Day 2 of 7',
    description: 'You always said you could slay any demon, Julie. Prove it \u2014 memorize the pattern and strike back.',
    unlockDate: '2026-02-08',
    type: 'kpop_sequence',
    clue: btoa('Look for Dronningens... (Queen\'s in Norwegian)'),
    icon: '\uD83D\uDDE1\uFE0F',
    theme: 'purple',
  },
  {
    id: 3,
    title: 'Spotlight',
    subtitle: 'Day 3 of 7',
    description: 'These words are all scrambled up, just like my thoughts whenever I see you. Unscramble them, Julie.',
    unlockDate: '2026-02-09',
    type: 'katseye_scramble',
    clue: btoa('...gate (meaning \'street\' in Norwegian)'),
    icon: '\uD83D\uDC31',
    theme: 'pink',
  },
  {
    id: 4,
    title: 'The Society Papers',
    subtitle: 'Day 4 of 7',
    description: 'A secret message has been intercepted, and only you can decode it. The ton is watching, Julie.',
    unlockDate: '2026-02-10',
    type: 'bridgerton_cipher',
    clue: btoa('The address number is 25'),
    icon: '\uD83D\uDCDC',
    theme: 'amber',
  },
  {
    id: 5,
    title: 'Directive',
    subtitle: 'Day 5 of 7',
    description: 'Everything has its place, Julie \u2014 just like you have yours in my heart. Sort these treasures where they belong.',
    unlockDate: '2026-02-11',
    type: 'walle_sort',
    clue: btoa('Something delicious awaits you there...'),
    icon: '\uD83E\uDD16',
    theme: 'yellow',
  },
  {
    id: 6,
    title: 'That Night in Hamburg',
    subtitle: 'Day 6 of 7',
    description: 'Remember the lights, the crowd, the music? Let\'s see how much you remember about our night out, Julie.',
    unlockDate: '2026-02-12',
    type: 'greenday_trivia',
    clue: btoa('Arrive at 18:00 on February 14th'),
    icon: '\uD83C\uDFB8',
    theme: 'green',
  },
  {
    id: 7,
    title: 'Lost in the City',
    subtitle: 'Day 7 of 7',
    description: 'One last adventure, Julie. Find your way through the winding streets \u2014 something special waits at the end.',
    unlockDate: '2026-02-13',
    type: 'london_maze',
    clue: btoa('The full address: Dronningens gate 25, Oslo. See you on Valentine\'s Day, Julie! \uD83D\uDC95'),
    icon: '\uD83C\uDDEC\uD83C\uDDE7',
    theme: 'blue',
  },
];
